steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/recaptcha-heroes-demo-image:tag1 \ 
    --build-arg projectId=PROJECT_NUMBER \ 
    --build-arg comitid=COMMITID \ 
    --build-arg apikey=APIKEY \
    --build-arg v3key=V3KEY \
    --build-arg v2key=V2KEY \
    --build-arg test2key=TEST2KEY \
    --build-arg test8key=TEST8KEY \
    --build-arg expresskey=EXPRESSKEY \
    --build-arg iapbackend=value \
    .
  automapSubstitutions: true
images:
- 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/recaptcha-heroes-demo-image:tag1'